# Generated by Django 3.0.3 on 2020-04-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password_lol', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('personal_image', models.ImageField(default='personal_images/default_personal_image.jpg', upload_to='personal_images')),
                ('bio', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('second_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('degree', models.CharField(blank=True, choices=[('High School', 'High School'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctoral', 'Doctoral')], max_length=30, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('url_of_instagram', models.URLField(blank=True, null=True)),
                ('url_of_facebook', models.URLField(blank=True, null=True)),
                ('url_of_twitter', models.URLField(blank=True, null=True)),
                ('url_of_youtube', models.URLField(blank=True, null=True)),
                ('CV', models.FileField(blank=True, default='CV_files/default_CV.pdf', null=True, upload_to='CV_files')),
                ('bio_skills', models.TextField(blank=True, null=True)),
                ('first_skill', models.CharField(blank=True, max_length=50, null=True)),
                ('percent_first_skill', models.IntegerField(blank=True, null=True)),
                ('second_skill', models.CharField(blank=True, max_length=50, null=True)),
                ('percent_second_skill', models.IntegerField(blank=True, null=True)),
                ('third_skill', models.CharField(blank=True, max_length=50, null=True)),
                ('percent_third_skill', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='logo_services/default_logo_service.png', upload_to='logo_services')),
                ('name_of_service', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Person')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='news_images/default_image_news.jpg', upload_to='news_images')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email_sender', models.EmailField(blank=True, max_length=254, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now=True, null=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Person')),
            ],
        ),
    ]
