# Generated by Django 3.0.3 on 2020-04-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
    ]
