# Generated by Django 3.0.3 on 2020-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20200408_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passwords_s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('password_lol', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
