# Generated by Django 3.0.3 on 2020-05-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20200518_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personal_image',
            field=models.FileField(default='personal_images/default_personal_image.jpg', upload_to='personal_images'),
        ),
    ]
