# Generated by Django 3.0.3 on 2020-06-01 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20200525_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Person'),
        ),
    ]
