# Generated by Django 3.0.3 on 2020-06-01 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_auto_20200602_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now=True, null=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Person')),
            ],
        ),
    ]
